### ISSUE TITLE
Qunit3 "assert.push is deprecated"

### ISSUE THREAD

**Issue by Rycochet** [JamesMGreene/qunit-assert-close#9]
Think they're making it quite a bit easier for the future, it still works in v2 but adds a little bit of log spam ;-)

```assert.push is deprecated and will be removed in QUnit 3.0. Please use assert.pushResult instead (https://api.qunitjs.com/assert/pushResult).```

[QUnit Upgrade Guide](https://qunitjs.com/upgrade-guide-2.x/#replace-qunit-push-with-this-pushresult)

Before:
```javascript
QUnit.assert.mod2 = function( value, expected, message ) {
    var actual = value % 2;
    QUnit.push( actual === expected, actual, expected, message );
};
```

After:
```javascript
QUnit.assert.mod2 = function( value, expected, message ) {
    var actual = value % 2;
    this.pushResult( actual === expected, actual, expected, message );
};
```

**Comment by Krinkle** [comment]
FYI: QUnit includes `assert.closeTo()` by default since 2.21.0.

**<https://qunitjs.com/api/assert/closeTo/>**

The built-in function is compatible and interopable with this plugin. Ensure you're using the latest QUnit, and update calls from `assert.close()` to `assert.closeTo()` in order to use it directly. (Background: <https://github.com/qunitjs/qunit/issues/1735>)
